apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
spec:
  template:
    spec:
      containers:
      - name: vllm
        env:
        - name: MODEL_ID
          value: meta-llama/Meta-Llama-3-70B-Instruct

