apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/protocol: https
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: gradio-ingress
  namespace: llm
spec:
  ingressClassName: kommander-traefik
  rules:
  - host: gradio.wh-nkp1.cloudnative.nvdlab.net
    http:
      paths:
      - backend:
          service:
            name: gradio
            port:
              number: 7860
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - gradio.wh-nkp1.cloudnative.nvdlab.net
    secretName: gradio.wh-nkp1.cloudnative.nvdlab.net