---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/protocol: https
    traefik.ingress.kubernetes.io/router.middlewares: llm-path-prefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: vllm-ingress
  namespace: llm
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: vllm-svc
            port:
              number: 80
        path: /vllm
        pathType: Prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: path-prefix
  namespace: llm
spec:
  stripPrefix:
    prefixes:
      - /vllm
