---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: llm-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: llm-llm-claim
    namespace: llm
  nfs:
    path: /llm-model-store
    server: files.romanticism.cloudnative.nvdlab.net
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-llm-claim
  namespace: llm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      storage: nfs
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: llm-volume