---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: lws-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 300Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: lws-pvc
    namespace: llm
  nfs:
    path: /llm-model-store
    server: files.romanticism.cloudnative.nvdlab.net
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: lws-pvc
  namespace: llm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      storage: nfs
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: lws-volume