apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nfs-pvc.yaml
- lws-4tp-1pp.yaml #baseline
#- lws-2tp-2pp.yaml
#- lws-1tp-4pp.yaml
#- lws-2tp-3pp.yaml
#- lws-2tp-4pp.yaml
#- lws-2tp-8pp.yaml
- service.yaml
- vllm-nginx-ingress.yaml
- ray-dashboard-ingress.yaml
- servicemonitor.yaml
- horizontal-pod-autoscaler.yaml
- gradio.yaml
- gradio-ingress.yaml
- grafana-nginx-ingress.yaml
#- nkp-kube-prometheus-stack-overrides.yaml